driver:
  kind: modern_ebpf
#falcoctl:
#  artifact:
#    install:
#      enabled: false
#    follow:
#      enabled: false
tty: true
resources:
  requests:
    cpu: 0m
    memory: 0Mi

falco:
  rules:
    - disable:
        rule: Drop and execute new binary in container
  priority: warning
