apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

namespace: contitrans

resources:
  - ns.yml

  - secrets.yml
  - service.yml
  - deployment.yml
  - ingress.yml
  - networkpolicy.yml
