---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-credentials
  namespace: fluentbit
spec:
  encryptedData:
    PASSWORD: AgBODqrx6s0kI5VUDZXEoahznGChbsXLVIXOCIWD4ad/aHnkUtLtc+CjdHPwiQ8tnQ2f+Orldsy1x2G0JiYBw5MWlo7wZG1MUk7Ji5aR4gucW42+LQIEla0OTpZMg4H/RzYp5lV9ofq1XocThq1H64+88KbnEdcrEhMW8dMbmakPWP2rqF/6ELOxhuh/nscragejSw0JTQZvERqztBZwHnRoTFCZnNvzfwOpO8kwfV1zDPR35UCZjRr8o9l2sU/mrTttuZPQx2UZdtg5GRJorRZIsgmH48ArjqC/gJkafsJHzjV1xvAyG5PGgfUHzsT6Vl13nWlf6RLvaXxuZvDhB+sTy2wO8Y/RQdzfhdTe/TrvG8rAjMczq3VDSA4pe9KiBGpxTcGVOIb0uK4dIOenljOc0XRZ5Uc7RJP1dGdu+beYK66CWyNknRDuszGlONGwXCfyv/cVEHpodGUkk+rxAJXZN8ZBBrMTryxOEdRjRRbmzxu7OD2ynLKCWR1CrvHWznm/kSiz5EmJUsiuvm72ZNKoApUrj9rl+LoYsXp0kUJydnTSCzxWjOlCwFeDzuBghvgrq+2FLQzPsOZ6j4VOifuAG6i30TbAUKOhHXJcjhkHa7akChi74gAVSoW7Tv+05oJwl+9ph+noS+3cM+i4Y9zdVbx8bjXUW73ARLKKg1EOdnGdM7bu1a7cYvGYXK33YDRDVFnwpUdS2g3NmaY9GgIOr7C9uRgZkaqKbKZ7DQwkeMfhVDPYsWDIy3pzQPDb9INI3ZNvgPS+sAvZQqFNenvqhHFFsbFkwzxIxwxzdqEIBLw0nqwdt53GDqgVmFSyx7j/DxKEITYJOm7nB8mWwD0Kq6jcoI+gkCw=
    USERNAME: AgA83ASotECDpsgOVFYJGjrUc0VE6E1QsFMZeYZVwYJcNBZpIbU+zuj9Vq/pEK2BtcV38foS4A/SmfiXs1WUMPwAqRKhBxDD1AryL0V8hb59J8CV5g3QHZ+4hNcMEFdUf0H9TpqYgk6b0EAXy0rfFSlr3YZb9c7uEdhu1UKpNxCu6lsp5CHj8Ns/E/yOxkcRwZKLgrsewjAeb1cPzu9g8vRg3ibdyZPBQjNOfJtU9pYrkuUZDbs8QzPv5q8tChZymsNxSuX0XJ0cZ4iZBBoeYdvQzb0W8M85vZPAsX6qbe2Jc5bNmTGl4OXtPqIyHXzGNgE3gEYr4G4mB+XqQ6lRItDTTSVAyg1MxuYUQEeNrm8E/ppOyTpF5Aicvx3uLACUjRCMQCQ2BA2Inu26NjCpmT6CeoJaxT34/rG1J0WQLbVg/fUKXbrO6R3A2NtX6TY7QIX51UbcbaQRvWa7LR+5KswouCWHpZt2gCi78TktOWYTz7I3mVEosbVSe8GHX8tBSAg60/mDGxjy9PFmxqsxlhgHR/iloOupBG8knVFaq39PgLcIISYzVeBFLDrSxTT4/rIAWtg0rVq6MVe1VuqiNnWvH+Pbcm3crw562e1gAe4ZG4Y84VTqPyKUxMgah/m2AWeahrrwnKEI52WNT5jn8dfmxj46/y3h/rjNb5VMkxoc4qH/l3vY9ZKgDl3sDL89B7VQe4HMs6c=
  template:
    metadata:
      name: loki-credentials
      namespace: fluentbit
    type: Opaque
