---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-credentials
  namespace: fluentbit
spec:
  encryptedData:
    LOKI_URL: AgAswreLQ383an7dJ1PQe9c6L6j3+KUxkTkb23hp43dlam1vVCfo8UHwh866PV8b1C7PdJIkRYAuWr5+uabZQ4oEOViDnZh/iAuk1NB8VXvYxdliv9X20/ldZUX8TIUONaXX0Evxd5whtE1IE2bcMEtqvItSY0uUZdy+CsuWHzE9ozqoOHv4OAV/jkfm5onyEutyZuB6KJ60ZnqahwvZp3Esm/URCROgrlHPJBeOyve79RkOCnA9R5VXb4M2IDSjTAnaTVo6sM95dii1XSwfeUPzxYfuPcWqD4Be4+jIkJTV964V91evuxiudRhqKiARYX49x0tDkqBA3+yvjU81uLrU8BhGVow/uAzMsbPMCP7dxcwnrxhIdIp56JnKiOKBbVqZ0Du+l/ie9Fr3UuWidM/VNyxZO3/mA7iLyauCpVqdTjVBOx+QX3UQry5QkY31tmAvwSwMemkrly2jigBYmbcGmorfhI+wpwtw9wb5/fOjci2pLIX0DGHtN2YBtN7JS0EXvdAFtzbUdmTQZcDO2e/hYkXFYPeoRdrNPa2wH3RTrdNO3T2eTj7GLGGqsGV0UoJvz8wMADoidEHdhneU7UepOo7oB+c7HbkFiykq1hm5lU4Pq55dej8kf0UFu5annQStkvU5wupslB44UjD/bUz27CJgekwpREj3rdE4VSLt2Z7uko5dvCfYJ7AVaeIwFBqJZr5Lqs1Tlg5bDBKvibcJUXG3Nx/954W7ckAKDoWz2fI0ZL9bzDEietQQYquuAy2tzVMh8PvJVoh0RGh1Cv7o4lA/54T7e3AI70Jinwd3mzXnM+Dn+3Qbn4MM45N62pA7fxV+I2tRcSqGK+i8K5axA/kwLhMk7UK7p6D6eh/b00tEtExqrpVEhFR7pyhTTapOQMEAgvrJAKL+6tIdAQ00Ex6gs9iIBQ==
  template:
    metadata:
      name: loki-credentials
      namespace: fluentbit
    type: Opaque
