---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-credentials
  namespace: fluentbit
spec:
  encryptedData:
    LOKI_URL: AgB17U3oLu3LXF+0qMRdWUmC8GFhnok+wweWuUPLwEz7yZjeWTHJAtoO4WPCrBYQIy9Tk+3aRch1UYSv8DFmAYKoPmmA9Wz/qTKvnk3xyokaQ9UTk4DqM/Yfdekw6ExrwYT6nmDKpgbu4D7kEL/Kvnq7cuogrMrBz0VLAANliEylvs7r9erk7pX8/dXMtm0Hw1en+6GakjwVyz3UcD+0dCPpvzAytwFvz3dIE+2Is4/+k/IzJmAAM+n41me9/vjXkogTcxi6ni5+wRypfj/ZveyT384t9W9MDW5aXdhe+S0KJGydXL0+liqFfFaU4BXOEg6lkYAdQHzgHKTu2hezObTYMmO9y+4BgRyA8feVS4VEbtI7PIJiArY5yFPCWPbmnvmnIIPvB5v39354ZhEFr3jmDQNnTL+vQy8qilZ4qwf/L+cX4yOQaQyc4SXeyQvkZERbuv8u8egfPC8MBDbCZ7mpm0iZjD/96OVBbDkilc0XRFoWg2D0bme66O8vv+3S1ioxz8FZR9pkGxNTKw/vLNXSzrhmXrtmZJc6sH+pS2znsMeatI3YS6hwNNmsU0N0UKoa93pHaBqvN6dibyWAKXOEOuniy1tsjGcaHSczZabQobeZMI9CYdOelkgocPXvRUPfFON9hH2P0rqQBqKNz7O/80QUuw8xLMNesmZ5Xm1XTOervZHuVELRiN2Mbgv0H5wTQPFDlk2qj4egwgIfLI6TdAG7r7LOvXkQdexgf5nnPQQ2c4Ru+BuuGmLyFElX8Hnc7td5LJGaWSJ2JBvz6VG7e1YFdLjjCflJQWl4gUJtj4bwTjnUqAoTXYpibmqGPeDWtw0JO6jdhaF3uKDEbwqAwdQ/E5ZEyhyCLAyqz0xRwl2DK+qf+Mr2BpSskEUkmyofAg==
  template:
    metadata:
      name: loki-credentials
      namespace: fluentbit
    type: Opaque
