apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: external-secrets
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: external-secrets
  ingress:
    - fromEndpoints:
        - {}
