apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: contibus
spec:
  image: registry.kvlk.hu/contibus
  secretRef:
    name: regcred
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: contibus-policy
spec:
  imageRepositoryRef:
    name: contibus
  policy:
    filterTags:
      pattern: "^(?P<number>[0-9]+)-[a-f0-9]+$"
      extract: "$build"
    numerical:
      order: asc
