apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: kalandozas-admin
spec:
  image: registry.kvlk.hu/kalandozas-admin
  interval: 2m
  secretRef:
    name: regcred
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: kalandozas-admin-policy
spec:
  imageRepositoryRef:
    name: kalandozas-admin
  filterTags:
    pattern: "^(?P<number>[0-9]+)-[a-f0-9]+$"
    extract: "$build"
  policy:
    numerical:
      order: asc
