---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgBY8J2xw7yEfcK7S3dE65cjF9pklezVv/ERn2SaTC64QYWHBWVfUoOq8vI5WB8iQkEvjcyxBh3c5MBE4OX+2f0iS3BLZdnGX+IqjEKDwppUG/+3CUcn5dBbHUwh8dXvlg/KEJZM5Bk1S4T806GbVFRy4EF/yip17eTO+UONMDKyRd58ExUm87R3Q0e59GtQhirbMu1h3pUOm6m2REE9L3yjF1aWi5spfcIiZNQae/EY4mdQvivWFpUam4zTKxfFQJ1OWwh5fZoUewFCc56J4X2iI+0Z2A9NwtwfvsGidYtVrV+4tShyZk4nERgUPNqiofSzDQbKysvTqxElWuMNjgcEdCxKBouQDfP7ruRFCQAv6zuznYpFAa6PpNxF3rQQRF+2nq8uua/ccPqZsKe398Fkt03XgSm2369Il3QSbMdLe38Ty9zr46GcM0IkxaTccJ658wBADKuwKa5N3K9JlX4K/mH8AB1/rHslLvF9qBBtpcZfk6zBAEW0gqTgHMT2At85XY/c6kqFwZAaLLcIlDnR/C/+7sZoHbQuR33GJnt+dkIgRsn1nyi6iC8rEvkQHO80iU787c8AUGXzSesSNAQzBtY+1YrypFAjItEBcnubVknJ1fUeZyG3LoraOBBjLQJfJbxrJ4xFi7DmftAKHml/q0MLUaqBFR0I8dCDnMiFA67BMMKvfAW1znLLwZQ0N0d/LXDho/oeCtqiSCPEHSeVC46csBujwt75rbHpyjSOcfEi4PgV33+aW7Bf4XF18KAgbZvVKeng1PlxKV/2CS95BeTQaLtcqdi38SvRST68iUgjs/emfjoKl9mhy1nq8UBcMJ5IfwlnBVxxKgK2UIFmAtT/vCj1
  template:
    metadata:
      name: regcred
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
