---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: contibus-env
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: contibus-env
  dataFrom:
    - extract:
        key: contibus-contibus-env
