---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAG43ylo2EkEZG4gyPg+5h6bOM4UGAO7IOv2uMkA4SmZKuct/JL4G+/DIU8WJPSpbsXfzXqoCaRrXl/5oOTbRDpJKYTF3mH29dnFYWdf3Fb35bo46iXXvJD8f3utOjUnspgR1d6P4LTXTCaXIJYA5lMooFtd+/0XTCjcWuk0abNJZP16Dt4bKK8MHNjzb8h0qScQTNGWCtlg5uf+ObmS69IEr4o6p16mvZXMTpwTICDX7O2N+N3VlhfGTTiXsc1apJw0YL2ivgbEYA6Th53GgWUk9zeUZ1o24BC3kLqhYfZTUJ8IcrtC8G5rD8TosOzRiKpGjqGoAK/usaCeAeLM/nBn0+1yzgfsfAQPpyFFhn25Ad0DQBmHxbhSI+f+jZO0A9qTiZtcnmuCPKcS17oVNNvMsqf5eirqR9F4k/pas187zgUnMrvmcJdMfzZQx8i/x9B22Lfkc9XwMu5BmQC6aAXtBlgzKmSrpvVUMJRLi+wS3iqSk7r21zIAg3AtLdPN/wjcEU81Kux4Nv0xHP27zgF7OB1o7TPRZz2jiLtdajbq1bN7OQiosuMVF7rjMuuDqP278jiERLZVsJok62rbnCMtnEjEjkQv+g79E12BncofpIRx0JY05zueIlJzVoUwx9I3hTNG67FkA3cC9b29z2qr06TSvDbAV3h+QOJiBPCeHJA+OCX0zU0Pr7FE4/XE1L/ESWxeF0af2c3wQCAuA30PdcLc7vweEGUnS66jmVyB+YbVT/H8LeO
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
