apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kalandozas-admin-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
spec:
  tls:
    - hosts:
        - admin.kalandozas.hu
      secretName: kalandozas-admin-tls
  rules:
    - host: admin.kalandozas.hu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kalandozas-admin-service
                port:
                  number: 80
