---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kalandozas-tls
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: kalandozas-tls
    template:
      type: kubernetes.io/tls
  dataFrom:
    - extract:
        key: kalandozas-kalandozas-tls
        decodingStrategy: Base64
