---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-credentials
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: loki-credentials
  dataFrom:
    - extract:
        key: fluentbit-loki-credentials
