apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kalandozas-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: |
      kube-system-redirect-https@kubernetescrd,
      kube-system-secure-chain@kubernetescrd,
      kube-system-cache@kubernetescrd
spec:
  tls:
    - hosts:
        - kalandozas.hu
      secretName: kalandozas-tls
  rules:
    - host: kalandozas.hu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kalandozas-service
                port:
                  number: 80
