apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kalandozas-ingress
spec:
  tls:
    - hosts:
        - kalandozas.hu
      secretName: kalandozas-tls
  rules:
    - host: kalandozas.hu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kalandozas-service
                port:
                  number: 80
