---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-webhook
  namespace: flux-system
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: discord-webhook
  data:
    - secretKey: address
      remoteRef:
        key: flux-system-discord-webhook
